### ISSUE TITLE
Projekt Kontext & Kick-Off

### ISSUE THREAD

**Issue by MarkusTiede** [digital-sustainability/civil42#4]
# 19.02.2024

## Agenda
- kurze Vorstellung
- Vorgehen / Pakete
- BFH / Puzzle Zusammenarbeit organisatorisch
- Varia

**Deadline: 6 Monate nach 30.01.2024 >> 30.07.2024**

### p4: Ziel 12.07.

# nächster Austausch: 05.03. - Inhalt(e)
- https://github.com/digital-sustainability/civil42/issues/5

**Comment by MarkusTiede** [comment]
# Frage
- [ ] Wie biased die Befrager sind?
- [x] Rollen / Erwartungen / Aufgaben im Projekt
  - Lead: @MarkusTiede 
  - Review / Feedback: @olibrian

**Comment by MarkusTiede** [comment]
# ToDo - @Kateschuetz
 - [x] Kontext & [Aufgabenstellung](https://github.com/digital-sustainability/civil42/blob/main/docs/antrag.md#umsetzbarkeit-der-resultate--aufgabe-des-forschungspartners)
   - [ ] https://github.com/digital-sustainability/civil42/issues/5
 - [x] Dokumentenablage : Switch-Drive - https://drive.switch.ch - bitte einmalig dort anmelden (am besten via SWITCH edu-ID)
 - [x] Github - [bitte einmalig dort anmelden fall noch nicht geschehen](https://github.com/signup) und hier einen Kommentar hinterlassen (für deinen Github-Handle)
